name = "calitekv3"
main = "worker/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "gd33v3"
database_id = "VOTRE_ID_GD33V3"

[[r2_buckets]]
binding = "R2"
bucket_name = "calitek-media"