name = "thewirev3"
main = "worker/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "thewirev3-db"
database_id = "ef62d103-a76b-496c-99d3-db598221e699"

[[r2_buckets]]
binding = "R2"
bucket_name = "thewirev3-media"